# Generated by Django 4.1.7 on 2023-03-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_superuser',
        ),
    ]
