# Generated by Django 4.1.7 on 2023-03-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
