# Generated by Django 4.1.7 on 2023-03-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='is_staff',
        ),
    ]
