# Generated by Django 4.1.7 on 2023-03-13 09:46

from basic.models import User
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_chessgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='black',
            field=models.ForeignKey(default='<basic.models.UserSerializer object at 0x7fc0037f93c0>', on_delete=models.SET('<basic.models.UserSerializer object at 0x7fc0037f85e0>'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white',
            field=models.ForeignKey(default='<basic.models.UserSerializer object at 0x7fc0037f93c0>', on_delete=models.SET('<basic.models.UserSerializer object at 0x7fc0037f85e0>'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
