# Generated by Django 4.1.7 on 2023-03-14 17:29

from basic.models import User
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_chessgame_black_chessgame_white'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='black',
            field=models.ForeignKey(default='<basic.models.UserSerializer object at 0x7fcfa1a446d0>', on_delete=models.SET('<basic.models.UserSerializer object at 0x7fcfa1a44760>'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white',
            field=models.ForeignKey(default='<basic.models.UserSerializer object at 0x7fcfa1a446d0>', on_delete=models.SET('<basic.models.UserSerializer object at 0x7fcfa1a44760>'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
