# Generated by Django 4.1.7 on 2023-05-02 11:01

from basic.models import User
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_alter_chessgame_black_alter_chessgame_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='black',
            field=models.ForeignKey(default='<basic.models.UserSerializer object at 0x7f447b4dd2d0>', on_delete=models.SET('<basic.models.UserSerializer object at 0x7f447b4dcc40>'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white',
            field=models.ForeignKey(default='<basic.models.UserSerializer object at 0x7f447b4dd2d0>', on_delete=models.SET('<basic.models.UserSerializer object at 0x7f447b4dcc40>'), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
